[tool.pipeline]
name = "pipeline"
version = "1.0.0"
description = "A complex data pipeline."
authors = ["Vladimir <avdeevvladimir@gmail.com>"]
readme = "README.md"

[tool.pipeline.dependencies]
python = "^3.10"
requests = "2.32.3"
flask = "3.1.0"
python-dotenv = "1.0.1"
pandas = "2.2.3"
matplotlib = "3.10.0"
mongoengine = "0.29.1"
pymongo = "4.10.1"
pydash = "8.0.4"
